name: Kenny Asteroids Benchmark

on:
  push:
    branches: [ kenney-asteroids-develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./kenney-asteroids/.version
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Run Benchmark
      run: dotnet run ./kenney-asteroids/KenneyAsteroids.Engine.Benchmark --configuration Release -- --filter * --exporters HTML --artifacts .\benchmark-report
    - name: Artifacts
      uses: actions/upload-artifact@v1
      with:
       name: ${{ format('kenney-asteroids-benchmark-v{0}.{1}', steps.version.outputs.content, github.run_number) }}
       path: benchmark-report