name: Kenny Asteroids Build

on:
  push:
    branches: [ master, kenney-asteroids-develop ]
  pull_request:
    branches: [ master, kenney-asteroids-develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 'Copy song2'
      shell: pwsh
      run: |
        $url = "https://api.github.com/repos/iivchenko/asset-storage/git/blobs/fc61d02f069f5d98b189a9ec0d903752b0ab21e5"
        $headers = @{ Authorization = "token ${{ secrets.ASSET_STORAGE }}"; Accept = "application/vnd.github.v3.raw" }
        $file = "kenney-asteroids/src/KenneyAsteroids.Desktop/Content/Music/game2.song.mp3"
        Invoke-WebRequest -Uri $url -Headers $headers -OutFile $file
    - name: 'Copy song3'
      shell: pwsh
      run: |
        $url = "https://api.github.com/repos/iivchenko/asset-storage/git/blobs/3d6f295a2176ea85399e744ea253cc9ee71f7c15"
        $headers = @{ Authorization = "token ${{ secrets.ASSET_STORAGE }}"; Accept = "application/vnd.github.v3.raw" }
        $file = "kenney-asteroids/src/KenneyAsteroids.Desktop/Content/Music/game3.song.mp3"
        Invoke-WebRequest -Uri $url -Headers $headers -OutFile $file
    - name: 'Copy song4'
      shell: pwsh
      run: |
        $url = "https://api.github.com/repos/iivchenko/asset-storage/git/blobs/bab333a67f4df2dc02f6fd6a99c0560d395df607"
        $headers = @{ Authorization = "token ${{ secrets.ASSET_STORAGE }}"; Accept = "application/vnd.github.v3.raw" }
        $file = "kenney-asteroids/src/KenneyAsteroids.Desktop/Content/Music/game4.song.mp3"
        Invoke-WebRequest -Uri $url -Headers $headers -OutFile $file
    - name: Set alpha or release suffix
      id: suffix
      if:  ${{ github.ref == 'refs/heads/master' }}
      run: echo '::set-output name=suffix::-alpha'
    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./kenney-asteroids/.version
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Build Pipeline Extensions
      run: dotnet build ./kenney-asteroids/src/KenneyAsteroids.PipelineExtension/KenneyAsteroids.PipelineExtension.csproj --configuration Release
    - name: Build Game
      run: dotnet build ./kenney-asteroids --configuration Release
    - name: Publish WinX64
      run: dotnet publish ./kenney-asteroids/src/KenneyAsteroids.Desktop/KenneyAsteroids.Desktop.csproj --configuration Release --runtime win-x64 --self-contained true -o ./publish/kenney-asteroids/win-x64
    - name: Artifacts
      uses: actions/upload-artifact@v1
      with:
       name: ${{ format('kenney-asteroids-win-x64-v{0}.{1}{2}', steps.version.outputs.content, github.run_number, steps.suffix.outputs.suffix) }}
       path: publish/kenney-asteroids/win-x64